### ISSUE TITLE
How to configure slimv for racket file type.

### ISSUE THREAD

**Issue by yangchenyun** [dkvasnicka/swank-racket#1]
Hi,
   This is probably not a question specifically related with swank-racket.
   I am a vim user and working with racket as well, through searching on swank server of racket, I stumbled upon your repo. 
   I have two problems to make it work automatically:
- how to configure vim to load slimv on `racket` filetype? slimv by default doesn't load for racket filetype.
- how to configure slimv to load the racket-swank server for filetype with racket?
  
  I guess you probably have a working configuration for racket+vim+slimv development, I will be very thankful if you could provide the solution for that.

Best,

**Comment by dkvasnicka** [comment]
Hi, for me the trick is to treat Racket files as Scheme files:

```
au BufNewFile,BufRead,BufReadPost *.rkt,*.rktl,*.rktd set filetype=scheme
```

It works well, Slimv has no problem with some of the specifics of Racket and all its features are available.

As for the Swank server: I am not aware of SLIMV being able to run a specific Swank for some particular type of lispy language. There is the `g:slimv_swank_cmd` option but that doesn't make much sense when you are using Slimv to edit multiple lisps (Clojure and Racket for me). But if Racket is the only (or almost the only) lisp you work with, set this config option to run swank-racket when no running Swank is detected by SLIMV (see http://kovisoft.bitbucket.org/tutorial.html)
